---
title: "Corona Virus Report"
author:
- familyname: XXXX
  othernames: XXX
  address: Monash Universtidy
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(ggplot2)
```

```{r Getting Data, echo = TRUE, message = FALSE, warning = FALSE}
data<- read_csv("Data/worldwidecases.csv")
```

```{r structure}
glimpse(data)
```

# Analysis

On looking at the datatype it can be seen that ‘date’ has an incorrect datatype. Date cannot be a character. The ‘data’ is converted to date time object. 
```{r}
data <- data %>% 
  mutate(dateRep = as.Date(dateRep, "%d/%m/%y"))

glimpse(data)
```

\section*{Country XX1 and YY1"}

\section2{Country India and Italy}

\section*{Country XX3 and YY3}

```{r confirmed cases by countries}
data_section2 <- data%>%
  filter(countriesAndTerritories %in% c("India","Italy"))

data_section2
```  


```{r confirmed cases by states}
data_section2 %>%
  group_by(countryterritoryCode) %>%
  summarise(confirmed_cases = sum(cases)) %>%
  kable(caption = "Table 1") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

We will be using logarithmic plot to plot.
```{r, fig.cap= "Figure 1"}
# Examining the situation in Australia
data_section2 %>%
  group_by(dateRep,countriesAndTerritories) %>%
  summarise(confirmed_cases = sum(cases)) %>%
  ggplot(aes(x = dateRep, y = confirmed_cases)) +
  geom_line() + scale_y_continuous(trans = "log10", labels = scales::comma)

```



